services:
    postgres:
        image: postgres
        container_name: postgres
        ports:
            - "5432:5432"
        env_file:
            - ../.env
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        volumes:
            - postgres:/var/lib/postgresql/data
volumes:
    postgres:
